# Generated by Django 4.2.1 on 2023-05-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="additional_availability",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="credentials",
            field=models.CharField(default="Default credentials", max_length=100),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="preferred_unit",
            field=models.CharField(default="No preference", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffmember",
            name="schedule",
            field=models.ManyToManyField(
                related_name="staff_members", to="staff_management.shift"
            ),
        ),
    ]
